// Generated by https://quicktype.io

export interface Alergia {
    id?: number;
    tipo: string;
    descripcion: string;
    paciente_id: number;
    createdAt?: string;
    updatedAt?: string;
}
