// Generated by https://quicktype.io

export interface Antecedente {
    id?: number;
    pesoRn: string;
    tipoParto: string;
    lactancia: string;
    paciente_id: number;
    createdAt?: string;
    updatedAt?: string;
}
